Re-initialize type service
dotnet/xcsync pull request #129
Opened 2024-10-10 01:01 UTC by haritha-mohan

test suite needs some work on organization..

2024-10-10 13:41 UTC, mcumming requested changes

2024-10-10 13:41 UTC, mcumming commented on test/xcsync.e2e.tests/usecases/GenerateThenSyncWithChangesTests.cs
> +	public async Task GenerateSync_MultipleFlowTest (string projectType, string tfm, Func<ITestOutputHelper, string, string, string, Task> xcodeChanges, Func<ITestOutputHelper, string, string, string, s
```suggestion
	public async Task GenerateAndSync_WithXcodeAndDotnetChanges_GeneratesChangesAsync (string projectType, string tfm, Func<ITestOutputHelper, string, string, string, Task> xcodeChanges, Func<ITestOutputHelper, string, string, string, string, Task> dotnetChanges)
```

2024-10-10 13:41 UTC, mcumming commented on test/xcsync.e2e.tests/usecases/GenerateThenSyncWithChangesTests.cs
> +
You should check that there are changes here.

2024-10-10 13:41 UTC, mcumming commented on test/xcsync.e2e.tests/usecases/GenerateThenSyncWithChangesTests.cs
> +		await Git (TestOutput, "-C", tmpDir, "add", ".").ConfigureAwait (false);
You should check that there are changes here.

2024-10-10 15:49 UTC, stephen-hawley requested changes

2024-10-10 15:49 UTC, stephen-hawley commented on src/xcsync/Workers/ChangeWorker.cs
> +		await new SyncContext (FileSystem, new TypeService (Logger!), message.Direction, ProjectPath, TargetDir, Framework, Logger).SyncAsync (cancellationToken);
Whenever I see a `!` assertion, I ask if this is avoidable.
In this case, I see the `Logger` variable being used several time before the assertion. This tells me that if `Logger` is null, this code will crash with a NRE before getting to the `!`.
I did a quick check on the source to serilog and it looks like there's no protection on the method. For example, if you implemented `Debug` like this:
```
public static void MyDebug(this ILogger? logger, string message)
{
    if (logger is null) return; // or exception?
    logger.Debug(message);
}
```
But it's not - it's a straight method.
What I would consider is:
1. put `#nullable enable` on this file and refactor appropriately.
2. if it makes sense for the `ILogger` to be null, then handle it appropriately before the `Debug` calls, the analyzer should be able to see that and not issue a warning so you shouldn't need the `!`; if not then the `!` isn't needed.

2024-10-15 17:08 UTC, mcumming approved these changes

2024-10-15 19:26 UTC, stephen-hawley approved these changes

2024-10-15 20:32 UTC, merged