fix duplicate register attribute during sync scenario
dotnet/xcsync pull request #163
Opened 2024-11-05 21:00 UTC by haritha-mohan

in the past, the register attribute was exclusively applied to the partial class defined in the *.designer.cs files.

however, xcsync uses roslyn for dotnet type processing and relies on the presence of the register attribute to detect if it is a type that should be synced to the Xcode environment.

so as is, after syncing the dotnet project is in a non-compilable state because of [CS0579 error](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0579?f1url=%3FappId%3Droslyn%26k%3Dk(CS0579)). the simple fix is to just remove the extra, no longer needed register attribute during the sync back.

before:
![Screenshot 2024-11-05 at 12 58 49 PM](https://github.com/user-attachments/assets/01ae13d6-37a0-4ac7-a7fc-034187fb734d)

after:
![Screenshot 2024-11-05 at 12 56 22 PM](https://github.com/user-attachments/assets/bf2db37c-d354-4181-aeaf-eb76d11b980a)

2024-11-05 21:32 UTC, dalexsoto commented
> the simple fix is to just remove the extra, no longer needed register attribute during the sync back.

Are we 100% sure about this? @rolfbjarne do we still need the Register attribute for NSObject derived subclasses? Or does the registrar takes care of it for us?

2024-11-05 21:37 UTC, haritha-mohan commented
@dalexsoto the register attribute is still present/required for the types, it's now just added to the partial class present in the original file rather than the *.designer.cs file. but if i'm missing something here, happy to adjust!

![Screenshot 2024-11-05 at 1 34 52 PM](https://github.com/user-attachments/assets/265601d2-16fb-4fb1-9abc-44c82bc4e78f)

2024-11-05 21:41 UTC, dalexsoto approved these changes

2024-11-06 09:32 UTC, rolfbjarne approved these changes

2024-11-06 16:50 UTC, mcumming commented
Can you provide a set of repro steps for this? I have yet to see this happen and would like to see what conditions this happens under.

2024-11-06 16:51 UTC, mcumming requested changes
Can you provide a set of repro steps for this? I have yet to see this happen and would like to see what conditions this happens under.

2024-11-06 16:56 UTC, haritha-mohan commented
> Can you provide a set of repro steps for this? I have yet to see this happen and would like to see what conditions this happens under.

@mcumming to repro the error, just add a action/outlet and run xcsync sync. the synced back project will contain the error

2024-11-06 19:40 UTC, stephen-hawley commented
Would it make sense to wrap the `[Register]` attribute in an `#if` instead of removing it entirely and then set the value before sync?
```
#if XCSYNC
[Register("whatever")]
#endif
```

2024-11-06 19:41 UTC, stephen-hawley approved these changes

2024-11-06 20:32 UTC, mcumming commented
> Would it make sense to wrap the `[Register]` attribute in an `#if` instead of removing it entirely and then set the value before sync?
> 
> ```
> #if XCSYNC
> [Register("whatever")]
> #endif
> ```

That would require modifying the users csproj file to set the XCSYNC directive, not something I want to do if it can be avoided. Technically, this change would be removing the generation of a duplicate attribute in the {class}.designer.cs file, since it already exists on the partial class definition in the {class}.cs file.

2024-11-07 00:23 UTC, haritha-mohan commented
users are expected to add the register attribute exclusively to the partial class counterpart in the *.designer.cs files. doing so will avoid the use case this pr addresses

2024-11-07 00:23 UTC, closed without merging